export const CURRENT_USER = 'CURRENT_USER';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const ADD_POINTS = 'ADD_POINTS';
export const ADD_POINTS_SUCCESS = 'ADD_POINTS_SUCCESS';
